"""name and description columns deleted from rooms table

Revision ID: aacd235c06c5
Revises: 4e0f4537a78c
Create Date: 2025-04-15 13:39:04.340996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacd235c06c5'
down_revision: Union[str, None] = '4e0f4537a78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###